epigenelabs/inmoose

.github/workflows/build_dist.yaml
CHANGELOG.md
MANIFEST.in
README.md
inmoose/__init__.py
inmoose/consensus_clustering/consensus_clustering.py
pyproject.toml
setup.py
tests/consensus_clustering/test_consensus_clustering.py

Python implementation of consensus clustering related to the issue #5 
Add cophenetic correlation and silouhette analysis to select the best number of cluster automatically
Test code with other algorithms than hierarchical clustering

Consensus clustering

---

CHANGELOG.md
README.md
docs/source/index.rst

Update the reference to our BMC Bioinformatic paper.

update reference of our pycombat article

---

CHANGELOG.md
inmoose/pycombat/covariates.py
inmoose/pycombat/pycombat_norm.py
inmoose/pycombat/pycombat_seq.py
tests/pycombat/test_covariates.py
tests/pycombat/test_pycombat.py
tests/pycombat/test_pycombatseq.py

Create a class `VirtualCohortInput` that stores and validates the input to the batch effect correction functions. Refactor existing code around this class.
See [the ticket](https://epigenelabsteam.atlassian.net/browse/CR-133).
This PR should improve the ability for users to check that their input is well-behaved, **prior to** calling the batch effect correction routines.

implement CR-133

---

CHANGELOG.md
inmoose/pycombat/covariates.py
inmoose/pycombat/pycombat_norm.py
inmoose/pycombat/pycombat_seq.py
tests/pycombat/test_pycombatseq.py

Fix issue #25 and add data format verification in VirtualCohortInput
Related Jira ticket [here](https://epigenelabsteam.atlassian.net/browse/CR-182?atlOrigin=eyJpIjoiN2Q0ZjE1MDk1NDhkNDZkMzg2YTY4ZGUwMDFmYThjNDMiLCJwIjoiaiJ9)
We want to improve DataFrame gestion for data parameter in pycombat_seq and pycombat_norm
Fix [the GitHub issue #25](https://github.com/epigenelabs/inmoose/issues/25) - Error when data type is DataFrame and na_cov_action="remove"
Add data parameter format check in  VirtualCohortInput, following [the Github issue #10](https://github.com/epigenelabs/inmoose/issues/10)

fix issue #25 and #10

---

CHANGELOG.md
docs/source/conf.py
inmoose/deseq2/DESeqTransform.py
inmoose/deseq2/vst.py
inmoose/pycombat/pycombat_norm.py
inmoose/pycombat/pycombat_seq.py

fix build of the documentation on readthedocs

fix documentation build

---

.github/workflows/build_dist.yaml
CHANGELOG.md
inmoose/consensus_clustering/consensus_clustering.py
inmoose/deseq2/DESeqDataSet.py
inmoose/deseq2/fitNbinomGLMs.py
inmoose/deseq2/results.py
inmoose/deseq2/weights.py
pyproject.toml
tests/deseq2/test_results.py

Closes #32 
Make sure `inmoose` works in as many environments as possible.

Support Python 3.12

---

.github/dependabot.yaml
.github/workflows/build_dist.yaml
CHANGELOG.md

Bump versions of github actions used in the workflows.
This PR groups several dependabot PRs.

Bump GitHub actions

---

CHANGELOG.md
inmoose/consensus_clustering/consensus_clustering.py

fix ylim stability plot for an easier interpretation 
code tested :

fix ylim stability plot

---

CHANGELOG.md
inmoose/limma/__init__.py
inmoose/limma/ebayes.py
tests/limma/test_tmixture.py

See [Jira card](https://epigenelabsteam.atlassian.net/browse/CR-263)
Splitting the port of `limma` into smaller PR to ease the integration process

CR-263 tmixture functions

---

CHANGELOG.md
inmoose/limma/__init__.py
inmoose/limma/dups.py
tests/limma/test_dups.py

See [Jira card](https://epigenelabsteam.atlassian.net/browse/CR-263)
Splitting the port of `limma` into smaller PR to ease the integration process

CR-263 duplicates from limma

---

inmoose/limma/__init__.py
inmoose/limma/contrasts.py
inmoose/limma/marraylm.py
inmoose/utils/__init__.py
inmoose/utils/linalg.py
tests/limma/test_contrasts.py
tests/limma/test_lmFit.py
tests/utils/test_linalg.py

See [Jira card](https://epigenelabsteam.atlassian.net/browse/CR-263)
Splitting the port of `limma` into smaller PR to ease the integration process

CR-263 contrasts-related functions from limma

---

CHANGELOG.md
README.md
docs/source/deseq.rst
docs/source/diffexp.rst
docs/source/index.rst
docs/source/limma.rst
pyproject.toml

Release 0.5.0

---

CHANGELOG.md
pyproject.toml

bump version to 0.5.1

---

CHANGELOG.md
pyproject.toml

Release a version for compatibility with numpy 2.0.0

Release 0.6.0

---

inmoose/edgepy/DGEList.py
inmoose/edgepy/addPriorCount.py
inmoose/edgepy/exactTest.py
inmoose/edgepy/topTags.py
inmoose/edgepy/validDGEList.py
tests/edgepy/test_DGEList.py
tests/edgepy/test_exactTest.py

See [CR-305]
Using a dataframe in class DGEList greatly helps.
[CR-305]: https://epigenelabsteam.atlassian.net/browse/CR-305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CR-305 Use DataFrame for counts in DGEList

---

inmoose/deseq2/results.py
inmoose/edgepy/glm_levenberg.py
inmoose/edgepy/glm_one_group.py
inmoose/edgepy/initialize_levenberg.py
inmoose/edgepy/mglmOneGroup.py
inmoose/limma/fitFDist.py
tests/deseq2/test_outlier.py

A swift cleanup PR to remove some warnings from chained assignment in pandas, as well as numpy warnings that surfaced after #56 .

Warnings cleanup

---

inmoose/__init__.py
inmoose/deseq2/plot.py
inmoose/deseq2/results.py
inmoose/diffexp/DEResults.py
inmoose/diffexp/__init__.py
inmoose/diffexp/plot.py
inmoose/edgepy/DGEExact.py
inmoose/edgepy/DGEGLM.py
inmoose/edgepy/DGELRT.py
inmoose/edgepy/exactTest.py
inmoose/edgepy/glmFit.py
inmoose/edgepy/glmQLFit.py
inmoose/edgepy/topTags.py
setup.py
tests/edgepy/test_exactTest.py
tests/edgepy/test_glm.py

See [CR-305]
This PR focuses on defining a common class for diff exp results and using it in the `edgepy` module.
[CR-305]: https://epigenelabsteam.atlassian.net/browse/CR-305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CR-305] harmonizing diff exp results (edgepy part)

---

CHANGELOG.md
inmoose/limma/toptable.py
tests/limma/test_lmFit.py

See [CR-305].
Follow up of #62 
[CR-305]: https://epigenelabsteam.atlassian.net/browse/CR-305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CR-305 harmonize diffexp results from limma

---

CHANGELOG.md
inmoose/diffexp/DEResults.py
tests/diffexp/test_DEResults.py

see [CR-352]
[CR-352]: https://epigenelabsteam.atlassian.net/browse/CR-352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CR-352 fix a faulty constructor

---

docs/source/deseq.rst

See [CR-353]
[CR-353]: https://epigenelabsteam.atlassian.net/browse/CR-353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CR-353 fix rendering of DEResults on readthedocs

---

AUTHORS
CHANGELOG.md
pyproject.toml

Release 0.7.1

---

pyproject.toml

See [CR-404].
[CR-404]: https://epigenelabsteam.atlassian.net/browse/CR-404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update numpy version constraint

---

inmoose/deseq2/wald.py
tests/deseq2/test_outlier.py

See [CR-391].
[CR-391]: https://epigenelabsteam.atlassian.net/browse/CR-391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix array indexing bug

---

inmoose/diffexp/meta.py
tests/diffexp/test_meta.py

See [CR-403]
NB: classified as "new feature" rather than "bug fix" since the expected behavior in the presence of NaN was not defined
[CR-403]: https://epigenelabsteam.atlassian.net/browse/CR-403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ensure meta-analysis is robust to NaN p-values

---

inmoose/limma/contrasts.py
tests/limma/test_contrasts.py

self-explanatory title ;-)
also [CR-424]
[CR-424]: https://epigenelabsteam.atlassian.net/browse/CR-424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CR-424 support underscores in contrast names in function makeContrasts

---

CHANGELOG.md
inmoose/cohort_qc/cohort_metric.py
inmoose/cohort_qc/qc_report.py
tests/cohort_qc/test_cohort_metric.py
tests/cohort_qc/test_qc_report.py

Self-explanatory title
also see [CR-426]
[CR-426]: https://epigenelabsteam.atlassian.net/browse/CR-426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix cohort QC report with 0 or 1 covariate

---

README.md

cosmetic improvements
see [CR-430]
[CR-430]: https://epigenelabsteam.atlassian.net/browse/CR-430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CR-430 logo and badges on README.md

---

inmoose/edgepy/DGEExact.py
inmoose/edgepy/DGELRT.py
inmoose/edgepy/topTags.py
tests/edgepy/test_glm.py

See [CR-431]
[CR-431]: https://epigenelabsteam.atlassian.net/browse/CR-431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix DGELRT to work with topTags

---

CHANGELOG.md
docs/source/diffexp.rst

See [CR-389]
[CR-389]: https://epigenelabsteam.atlassian.net/browse/CR-389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CR-389 add meta-analysis examples to the documentation

---

docs/source/clustering.rst
docs/source/index.rst
pyproject.toml

See [CR-443]
[CR-443]: https://epigenelabsteam.atlassian.net/browse/CR-443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CR-443 add a doc page aobut consensus clustering

---

CHANGELOG.md
inmoose/pycombat/covariates.py
inmoose/pycombat/pycombat_norm.py
inmoose/pycombat/pycombat_seq.py
tests/pycombat/test_pycombat.py
tests/pycombat/test_pycombatseq.py

See [CR-440]
[CR-440]: https://epigenelabsteam.atlassian.net/browse/CR-440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CR-440 allow AnnData as input of pycombat functions

---

pyproject.toml

set minimal version of scipy

---

inmoose/deseq2/dispersions.py

See [CR-462]
[CR-462]: https://epigenelabsteam.atlassian.net/browse/CR-462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CR-462 clarify a message to the user

---

README.md
docs/source/diffexp.rst
docs/source/index.rst
docs/source/pycombat.rst
inmoose/edgepy/dispCoxReid.py

See [CR-474].
Make sure our papers are properly referenced + cosmetic doc fixes.
[CR-474]: https://epigenelabsteam.atlassian.net/browse/CR-474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CR-474 update paper references

---

CHANGELOG.md
docs/source/deseq.rst

[CR-466](https://epigenelabsteam.atlassian.net/browse/CR-466?atlOrigin=eyJpIjoiNThhNjYyYzFhZTYyNGUwZjk1ZjA3NzgyNzcwNTc2NGMiLCJwIjoiaiJ9)
improve DESeq documentation on Note on factor levels
[CR-466]: https://epigenelabsteam.atlassian.net/browse/CR-466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add more info in deseq2 doc Note on factor levels

---

inmoose/cohort_qc/cohort_metric.py
inmoose/consensus_clustering/consensus_clustering.py
inmoose/deseq2/deseq2_cpp.py
inmoose/deseq2/dispersions.py
inmoose/deseq2/fitNbinomGLMs.py
inmoose/deseq2/results.py
inmoose/deseq2/wald.py
inmoose/limma/toptable.py
inmoose/pycombat/covariates.py

See [CR-467]
[CR-467]: https://epigenelabsteam.atlassian.net/browse/CR-467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CR-467 allow "log2FoldChange" to sort_by in limma

---

.github/workflows/build_dist.yaml
tox.ini

Test `inmoose` against Python 3.13.
See [CR-508].
[CR-508]: https://epigenelabsteam.atlassian.net/browse/CR-508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add support for Python 3.13

---

inmoose/cohort_qc/qc_report.html
inmoose/cohort_qc/qc_report.py
pyproject.toml
setup.py
tests/cohort_qc/test_qc_report.py
tox.ini

CR-444 : Beautify the cohort QC report

---

docs/source/deseq.rst
inmoose/deseq2/results.py
inmoose/diffexp/DEResults.py
inmoose/diffexp/plot.py
inmoose/edgepy/topTags.py
inmoose/limma/toptable.py
tests/deseq2/test_outlier.py
tests/edgepy/test_exactTest.py
tests/edgepy/test_glm.py
tests/limma/test_lmFit.py

See [CR-563]
[CR-563]: https://epigenelabsteam.atlassian.net/browse/CR-563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CR-563 harmonize the reporting of adjusted p-values in diffexp modules

---

inmoose/edgepy/edgepy_cpp/edgepy_cpp.pyx

See [CR-568]
[CR-568]: https://epigenelabsteam.atlassian.net/browse/CR-568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CR-568 fix an import in Cython

---

inmoose/cohort_qc/cohort_metric.py

This PR aims to add `StandardScaler` to PCA transformation in`CohortMetric` class.

Add StandardScaler to CohortMetric PCA transformation

---

CHANGELOG.md
pyproject.toml

bump version to 0.7.6

---

CHANGELOG.md
pyproject.toml

bump version to 0.7.7

---

README.md

Updating Usage Examples to create and save a `QCReport`
Closes #137

Updating QC Report section in README.md

---

pyproject.toml

See [CR-656]
[CR-656]: https://epigenelabsteam.atlassian.net/browse/CR-656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CR-656 constraint scipy version

---

CHANGELOG.md
docs/source/index.rst
pyproject.toml

bump to version 0.7.8

---

CHANGELOG.md
pyproject.toml

See [CR-663]
[CR-663]: https://epigenelabsteam.atlassian.net/browse/CR-663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CR-663 comply with PEP639
